version: '3'
services:
  postgres14:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=go_finance
    ports:
      - '5432:5432'